language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

install: composer install

script:
  - vendor/bin/phpunit --coverage-clover clover.xml

after_script:
  - php vendor/bin/coveralls --exclude-no-stmt
